# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 75b46171ece192107f8e2e5fd5c1a953c078cd855c66dd90bd740679e0451cbad915093bf7ea931cd59027d3f30175b267501009c3392efea0cffd0651a8fc80

test:
  secret_key_base: e853b46a4e231d3ab4212f9d69ca963c87acb36f058d8f53d89724bb7a7ca9cbc2a40a33fbaabf356ed1e9003e11ecfa2536de919c8d20dfb744109032eda2d3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
